name: "New CAP (Constitutional Amendment Proposal)"
description: "Propose a new CAP via a structured form. Generates a CAP-XXXX.md file via PR."
title: "CAP-XXXX: <short descriptive title>"
labels:
  - CAP
body:
  - type: input
    id: cap_number
    attributes:
      label: CAP
      description: "Four digits, e.g. 0001"
      placeholder: "0001"
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Title
      description: "Title of the Constitutional Amendment Proposal"
      placeholder: "[Title of the Constitutional Amendment Proposal]"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: "Choose one category"
      options:
        - Guardrails
        - Meta
        - Constitution
        - Standards
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Draft
        - Review
        - Ratified
        - Withdrawn
    validations:
      required: true

  - type: textarea
    id: authors
    attributes:
      label: Authors
      description: "One per line, e.g. Name <@GitHubHandle>"
      placeholder: |
        Ada Lovelace <@ada>
        Charles Babbage <@babbage>
      render: text
    validations:
      required: true

  - type: textarea
    id: implementors
    attributes:
      label: Implementors
      description: "One per line. Use 'N/A' if none."
      placeholder: |
        N/A
      render: text
    validations:
      required: true

  - type: textarea
    id: solution_to
    attributes:
      label: Solution-To (CIS references)
      description: "One per line, e.g. CIS-0001"
      placeholder: |
        CIS-0001
      render: text

  - type: textarea
    id: discussions
    attributes:
      label: Discussions (URLs)
      description: "One per line (GitHub Discussions or relevant links)"
      placeholder: |
        https://github.com/[org]/CAP/discussions/123
      render: text

  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      description: "~200 words summarizing the amendment and governance issue."
      placeholder: "A short (~200 words) summary ..."
      render: markdown
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation: Why is this CAP necessary?
      description: "Explain the governance problem, stakeholders, and links to CIS."
      render: markdown
    validations:
      required: true

  - type: textarea
    id: spec
    attributes:
      label: Amendment Specification (canonical text)
      description: "Provide the exact text of the proposed constitutional change or addition."
      render: markdown
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale: How does this CAP achieve its goals?
      render: markdown
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Path to Ratification - Acceptance Criteria
      render: markdown

  - type: textarea
    id: implementation
    attributes:
      label: Path to Ratification - Implementation Plan
      render: markdown

  - type: textarea
    id: versioning
    attributes:
      label: Versioning (Optional)
      render: markdown

  - type: textarea
    id: references
    attributes:
      label: References (Optional)
      render: markdown

  - type: checkboxes
    id: confirm
    attributes:
      label: Confirmation
      options:
        - label: "I confirm the CAP number is four digits (e.g., 0001) and unique."
          required: true
