name: 📝 New CAP Proposal
description: Submit a new Cardano Amendment Proposal (CAP)
title: "CAP Proposal: <short descriptive title>"
labels: ["proposal", "CAP"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Cardano Amendment Proposal (CAP)
        Please fill out this form to propose a new CAP.  
        Read the [CAP Process (CAP-0001)](https://github.com/[your-org]/CAPs/blob/main/CAP-0001/README.md) before submission.

  - type: input
    id: title
    attributes:
      label: CAP Title
      description: The proposed title of your CAP.
      placeholder: e.g. "Guardrails — Parameter Thresholds"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the appropriate CAP category.
      options:
        - Meta
        - Constitution
        - Guardrails
        - Standards
    validations:
      required: true

  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      description: A short (~200 words) summary of the problem and proposed governance change.
      placeholder: e.g. "This CAP proposes introducing a new threshold guardrail for ... "
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this CAP necessary? What challenges or governance gaps does it address?
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true

  - type: textarea
    id: specification
    attributes:
      label: Specification
      description: Describe the proposal in technical and procedural detail — what governance rule, process, or standard is being proposed?
      placeholder: |
        Define the process, governance mechanism, or standard here.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Explain your design choices, alternatives considered, and how this proposal solves the problem.
      placeholder: e.g. "We considered X but chose Y because..."
    validations:
      required: false

  - type: textarea
    id: path_to_ratification
    attributes:
      label: Path to Ratification
      description: Describe the acceptance criteria and implementation plan for this CAP to become ratified.
      placeholder: |
        - Acceptance Criteria:
        - Implementation Plan:
    validations:
      required: true

  - type: input
    id: authors
    attributes:
      label: Authors
      description: List all authors with contact info.
      placeholder: e.g. "Jane Doe <jane@domain.org>"
    validations:
      required: true

  - type: input
    id: implementors
    attributes:
      label: Implementors
      description: (Optional) List implementors or teams responsible.
      placeholder: e.g. "Governance Tech WG"

  - type: textarea
    id: discussions
    attributes:
      label: Discussion Links
      description: Provide URLs for GitHub Discussions, Forum posts, or other related threads.
      placeholder: e.g. "https://github.com/[your-org]/CAPs/discussions/123"

  - type: dropdown
    id: license
    attributes:
      label: License
      description: Choose the license under which your CAP is published.
      options:
        - CC-BY-4.0
        - Apache-2.0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ✅ **Before submitting**
        - Review your CAP for clarity and completeness.
        - Ensure no implementation code is included.
        - Link to any related Constitution Issue Statement (CIS) or prior CAPs.
        - Submissions are triaged and reviewed by CAP Editors.

