name: Create Amendment Proposal
description: Create a new CAP or CIS using the structured wizard format
title: "[CAP/CIS] Your proposal title here"
labels: ["Deliberation-Period"]
body:
  - type: markdown
    attributes:
      value: |
        # Amendment Proposal Wizard
        Complete this form to create a new Constitution Amendment Proposal (CAP) or Constitutional Information Submission (CIS).

  - type: dropdown
    id: proposal_type
    attributes:
      label: Proposal Type
      description: Choose whether this is a CAP or CIS
      options:
        - CAP (Constitution Amendment Proposal)
        - CIS (Constitutional Information Submission)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the category that best fits your proposal
      options:
        - Constitution
        - Meta
        - Guardrails
        - Supporting
        - Other
    validations:
      required: true

  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      description: Provide a brief summary of your proposal (1-2 paragraphs)
      placeholder: "Summarize the key points of your proposal..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this change is needed. What problem does it solve?
      placeholder: "Explain the motivation and rationale for this proposal..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Structured Revisions (for CAPs only)
        If this is a CAP, add the specific constitutional text you're changing and your proposed revisions below.

  - type: textarea
    id: revision_1_original
    attributes:
      label: "Revision #1 - Original Text"
      description: "Paste the exact constitutional text you want to change"
      placeholder: "Paste the original text from the constitution..."

  - type: textarea
    id: revision_1_proposed
    attributes:
      label: "Revision #1 - Proposed Change"
      description: "Describe your proposed revision to this text"
      placeholder: "Describe how you would change this text..."

  - type: textarea
    id: revision_2_original
    attributes:
      label: "Revision #2 - Original Text (optional)"
      description: "If making multiple changes, add the second original text here"
      placeholder: "Leave blank if only one change..."

  - type: textarea
    id: revision_2_proposed
    attributes:
      label: "Revision #2 - Proposed Change (optional)"
      description: "Describe your proposed revision to this text"
      placeholder: "Leave blank if only one change..."

  - type: textarea
    id: exhibits
    attributes:
      label: Supporting Exhibits (Links)
      description: "Add links to any supporting materials, research, or resources"
      placeholder: |
        - [Research Paper](https://example.com/paper)
        - [Technical Analysis](https://example.com/analysis)

  - type: textarea
    id: co_authors
    attributes:
      label: Co-Authors
      description: "Tag any co-authors using @username format (one per line)"
      placeholder: |
        @alice
        @bob
        @charlie

  - type: markdown
    attributes:
      value: |
        ## Metadata
        The following will be automatically added when you submit:
        - **Type**: CAP or CIS (based on your selection)
        - **Category**: Based on your selection
        - **License**: CC-BY-4.0
        - **Review Period**: 30 days from creation
        - **Status**: Deliberation-Period

  - type: checkboxes
    id: acknowledgments
    attributes:
      label: Acknowledgments
      description: Please confirm you've read and understand these guidelines
      options:
        - label: "I have read the [CAP/CIS Guidelines](../WORKFLOW_GUIDE.md)"
          required: true
        - label: "I understand this proposal will be open for community discussion for 30 days"
          required: true
        - label: "I understand I can edit this proposal after creation"
          required: true
