name: "Issue Statement (CIS)"
description: "Report a problem or issue."
title: "[CIS]: "
labels: ["CIS", "Proposed", "Deliberation-Period"]
body:
  - type: markdown
    attributes:
      value: |
        ### CIS Form
        Use this to report a problem that needs attention.

  - type: textarea
    id: abstract
    attributes:
      label: Summary
      description: A short summary of the issue.
      placeholder: What is the problem?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Pick the category that fits best.
      options:
        - Meta (Process or framework issues)
        - Constitution (Text issues)
        - Guardrails (Technical or monetary limit issues)
        - Supporting (Guidance or extra doc issues)
        - Other (Anything else)
    validations:
      required: true

  - type: textarea
    id: statement_of_problem
    attributes:
      label: Explanation
      description: Give more details on why this is an issue.
      placeholder: Explain the problem...
    validations:
      required: true

  - type: textarea
    id: problem_identification
    attributes:
      label: Problem Details
      description: Cite the specific part where the problem exists.
      placeholder: |
        ### Section: [Article X]
        **Original Text:** [Paste here]
        **The Problem:** [Describe it here]
    validations:
      required: true

  - type: textarea
    id: exhibits
    attributes:
      label: Links and Files
      description: Links to evidence or extra info.
      placeholder: "https://..."

  - type: checkboxes
    id: acknowledgments
    attributes:
      label: Confirmations
      options:
        - label: I understand this starts a 30-day deliberation period.
          required: true
        - label: I agree to license this under CC-BY-4.0.
          required: true
