name: "New Cardano Amendment Proposal (CAP)"
description: "Propose a change to the Constitution or Governance Rules"
title: "[CAP-PROPOSAL]: "
labels: ["Proposed", "Deliberation-Period"]
body:
  - type: markdown
    attributes:
      value: |
        ### Welcome! 
        Filling out this form starts your **mandatory 30-day deliberation period**. 
  - type: input
    id: title
    attributes:
      label: "Proposal Title"
      description: "A short, descriptive name for your proposal."
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: "Category"
      description: "Select the area of governance this proposal affects."
      options:
        - Constitution
        - Guardrails
        - Standards
        - Meta
    validations:
      required: true
  - type: textarea
    id: abstract
    attributes:
      label: "Abstract"
      description: "A short (~200 words) summary of the proposed change."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why is this change necessary? What problem does it solve?"
    validations:
      required: true
  - type: textarea
    id: specification
    attributes:
      label: "Specification"
      description: "The detailed proposal—the exact rules, standards, or text being changed."
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: "Rationale"
      description: "Explain your design choices and any alternative approaches you considered."
    validations:
      required: true
  - type: textarea
    id: ratification
    attributes:
      label: "Path to Ratification"
      description: "What criteria must be met for this CAP to become Active (e.g., specific vote thresholds)?"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: "Final Acknowledgements"
      options:
        - label: "I understand this starts a mandatory 30-day deliberation period."
          required: true
        - label: "I agree to license this proposal under CC-BY-4.0."
          required: true
