name: "Amendment Proposal (CAP)"
description: "Submit a proposal to change the Constitution."
title: "[CAP]: "
labels: ["CAP", "Draft"]
body:
  - type: markdown
    attributes:
      value: |
        ### CAP Form
        Fill out the details below to propose an amendment.

  - type: textarea
    id: abstract
    attributes:
      label: Summary
      description: A short summary of your proposal.
      placeholder: What is this proposal about?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Pick the category that fits best.
      options:
        - Meta (Process or framework changes)
        - Constitution (Direct text changes)
        - Guardrails (Technical or monetary limits)
        - Supporting (Guidance or extra docs)
        - Other (Anything else)
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why?
      description: Why is this change needed?
      placeholder: Explain the reasoning...
    validations:
      required: true

  - type: textarea
    id: specification
    attributes:
      label: Revisions
      description: List the original text and your proposed change.
      placeholder: |
        ### Section: [Article X]
        **Original Text:** [Paste here]
        **Proposed Change:** [Type change here]
    validations:
      required: true

  - type: textarea
    id: exhibits
    attributes:
      label: Links and Files
      description: Links to research, files, or extra info.
      placeholder: "https://..."
    
  - type: checkboxes
    id: acknowledgments
    attributes:
      label: Confirmations
      options:
        - label: I understand this starts a 30-day deliberation period.
          required: true
        - label: I agree to license this under CC-BY-4.0.
          required: true
