name: 🧭 New Constitution Issue Statement (CIS)
description: Submit a new CIS to articulate a constitutional/governance issue and its context
title: "CIS Proposal: <short descriptive title>"
labels: ["CIS", "governance", "proposal"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Constitution Issue Statement (CIS)
        Use this form to define a constitutional/governance issue, its context, and the open questions the community should address.
        Please read the CIS process guidance before submitting.

  # ── Metadata ───────────────────────────────────────────────────────────────────

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Choose the best-fit topic area.
      options:
        - Governance
        - Constitution
        - Process
        - Guardrails / Risk
        - Interpretation / Clarification
        - Other
    validations:
      required: true

  - type: textarea
    id: authors
    attributes:
      label: Authors
      description: List all authors (name and optional handle/contact).
      placeholder: |
        - Jane Doe <@jane-doe>
        - John Smith <john@domain.org>
    validations:
      required: true

  - type: textarea
    id: discussions
    attributes:
      label: Discussion Links
      description: Link to GitHub Discussions, forums, calls/notes, etc.
      placeholder: |
        https://github.com/<org>/<repo>/discussions/123
        https://forum.cardano.org/t/<topic-id>
    validations:
      required: false

  - type: textarea
    id: related_caps
    attributes:
      label: Related / Proposed Amendments (CAPs)
      description: Link to any CAPs this issue motivates or relates to (if any).
      placeholder: |
        https://github.com/<org>/CAPs/pull/42
        CAP-0007
    validations:
      required: false

  # ── Core CIS Sections ─────────────────────────────────────────────────────────
  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      description: ~200-word summary of the constitutional issue.
      placeholder: Provide a concise summary of the issue and why it matters.
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: Background
      description: Historical, procedural, or constitutional context for why this issue exists.
      placeholder: Describe relevant history, prior decisions, and contextual factors.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Clear, scoped description of the constitutional/governance issue.
      placeholder: Define the issue, who/what it affects, and boundaries of scope.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: How this issue affects governance, stakeholders, or the constitution.
      placeholder: Explain risks, legitimacy concerns, centralization risks, etc.
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: Prioritized outcomes the community seeks by addressing this issue.
      placeholder: |
        - Increase participation by ...
        - Improve representation by ...
        - Enhance transparency by ...
    validations:
      required: true

  - type: textarea
    id: open_questions
    attributes:
      label: Open Questions
      description: Questions that any solution (e.g., a CAP) should aim to answer.
      placeholder: |
        - What participation threshold defines legitimacy?
        - Should dReps meet minimum activity levels?
        - Which incentives would drive meaningful engagement?
    validations:
      required: true

  # ── Optional helpful sections (seen in examples) ──────────────────────────────
  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases (Optional)
      description: Concrete scenarios illustrating the problem.
      placeholder: |
        1) Governance action fails quorum due to low turnout...
        2) Delegators unknowingly delegate to inactive dReps...
    validations:
      required: false

  - type: textarea
    id: next_steps
    attributes:
      label: Proposed Next Steps (Optional)
      description: Non-binding ideas for what investigations or CAPs might follow.
      placeholder: |
        - Research incentive models for participation
        - Draft CAP on minimum dRep activity standards
        - Build transparency dashboards for turnout
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References (Optional)
      description: Link supporting docs, standards, or related materials.
      placeholder: |
        - Prior discussions, papers, dashboards, datasets
    validations:
      required: false

  # ── License + Submission checklist ────────────────────────────────────────────
  - type: dropdown
    id: license
    attributes:
      label: License
      description: CIS documents should be explicitly licensed.
      options:
        - CC-BY-4.0
        - Apache-2.0
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Submission Checklist
      options:
        - label: I confirm this issue contains no implementation code (links are fine).
          required: true
        - label: I have summarized off-platform feedback (if any) in the discussion links.
          required: false
        - label: I understand editors may adjust metadata and directory structure on merge.
          required: true
