name: "Council Amendment Proposal (CAP)"
description: "Draft a formal amendment for the Cardano Constitution."
title: "[CAP]: "
labels: ["CAP", "Draft"]
body:
  - type: markdown
    attributes:
      value: |
        ### Institutional Intake: CAP
        Thank you for contributing to the governance layer. Please ensure your abstract is concise and your motivation clear.

  - type: textarea
    id: abstract
    attributes:
      label: Executive Abstract
      description: A high-level summary of this proposal.
      placeholder: Summarize your amendment...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Working Category
      description: Choose the classification that best fits your proposal.
      options:
        - Meta (CIP process or governance framework changes)
        - Constitution (Direct amendments to the text)
        - Guardrails (Technical and monetary guardrail systems)
        - Supporting (Technical guidance or supporting documentation)
        - Other (Proposals falling outside defined categories)
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this change necessary?
      placeholder: Provide the logic and necessity behind this entry...
    validations:
      required: true

  - type: textarea
    id: specification
    attributes:
      label: Structured Revisions (Contextual)
      description: |
        Please provide the specific section and text you are referencing from the Constitution, followed by your proposed change.
      placeholder: |
        ### Section: [Article X]
        **Original Text:** [Paste here]
        **Proposed Revision:** [Type change here]
    validations:
      required: true

  - type: textarea
    id: exhibits
    attributes:
      label: Institutional Assets
      description: Links to research, datasets, or external specifications.
      placeholder: "https://..."
    
  - type: checkboxes
    id: acknowledgments
    attributes:
      label: Governance Acknowledgments
      options:
        - label: I understand this starts a mandatory 30-day deliberation period.
          required: true
        - label: I agree to license this document under CC-BY-4.0.
          required: true
